// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package org.wxd.boot.net.message;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqRemoteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqRemote)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 rpcId = 1;</code>
     * @return The rpcId.
     */
    long getRpcId();

    /**
     * <pre>
     *1表示压缩过
     * </pre>
     *
     * <code>int32 gzip = 2;</code>
     * @return The gzip.
     */
    int getGzip();

    /**
     * <pre>
     *执行的命令
     * </pre>
     *
     * <code>string cmd = 3;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <pre>
     *执行的命令
     * </pre>
     *
     * <code>string cmd = 3;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <pre>
     *用JsonObject来解析
     * </pre>
     *
     * <code>string params = 4;</code>
     * @return The params.
     */
    java.lang.String getParams();
    /**
     * <pre>
     *用JsonObject来解析
     * </pre>
     *
     * <code>string params = 4;</code>
     * @return The bytes for params.
     */
    com.google.protobuf.ByteString
        getParamsBytes();

    /**
     * <pre>
     *用于验证的消息
     * </pre>
     *
     * <code>string rpcToken = 5;</code>
     * @return The rpcToken.
     */
    java.lang.String getRpcToken();
    /**
     * <pre>
     *用于验证的消息
     * </pre>
     *
     * <code>string rpcToken = 5;</code>
     * @return The bytes for rpcToken.
     */
    com.google.protobuf.ByteString
        getRpcTokenBytes();
  }
  /**
   * <pre>
   *执行同步等待消息
   * </pre>
   *
   * Protobuf type {@code ReqRemote}
   */
  public static final class ReqRemote extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReqRemote)
      ReqRemoteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqRemote.newBuilder() to construct.
    private ReqRemote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqRemote() {
      cmd_ = "";
      params_ = "";
      rpcToken_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReqRemote();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wxd.boot.net.message.Rpc.internal_static_ReqRemote_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wxd.boot.net.message.Rpc.internal_static_ReqRemote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wxd.boot.net.message.Rpc.ReqRemote.class, org.wxd.boot.net.message.Rpc.ReqRemote.Builder.class);
    }

    public static final int RPCID_FIELD_NUMBER = 1;
    private long rpcId_ = 0L;
    /**
     * <code>int64 rpcId = 1;</code>
     * @return The rpcId.
     */
    @java.lang.Override
    public long getRpcId() {
      return rpcId_;
    }

    public static final int GZIP_FIELD_NUMBER = 2;
    private int gzip_ = 0;
    /**
     * <pre>
     *1表示压缩过
     * </pre>
     *
     * <code>int32 gzip = 2;</code>
     * @return The gzip.
     */
    @java.lang.Override
    public int getGzip() {
      return gzip_;
    }

    public static final int CMD_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cmd_ = "";
    /**
     * <pre>
     *执行的命令
     * </pre>
     *
     * <code>string cmd = 3;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *执行的命令
     * </pre>
     *
     * <code>string cmd = 3;</code>
     * @return The bytes for cmd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object params_ = "";
    /**
     * <pre>
     *用JsonObject来解析
     * </pre>
     *
     * <code>string params = 4;</code>
     * @return The params.
     */
    @java.lang.Override
    public java.lang.String getParams() {
      java.lang.Object ref = params_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        params_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用JsonObject来解析
     * </pre>
     *
     * <code>string params = 4;</code>
     * @return The bytes for params.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParamsBytes() {
      java.lang.Object ref = params_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        params_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RPCTOKEN_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object rpcToken_ = "";
    /**
     * <pre>
     *用于验证的消息
     * </pre>
     *
     * <code>string rpcToken = 5;</code>
     * @return The rpcToken.
     */
    @java.lang.Override
    public java.lang.String getRpcToken() {
      java.lang.Object ref = rpcToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rpcToken_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用于验证的消息
     * </pre>
     *
     * <code>string rpcToken = 5;</code>
     * @return The bytes for rpcToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRpcTokenBytes() {
      java.lang.Object ref = rpcToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rpcToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rpcId_ != 0L) {
        output.writeInt64(1, rpcId_);
      }
      if (gzip_ != 0) {
        output.writeInt32(2, gzip_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cmd_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(params_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, params_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rpcToken_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, rpcToken_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rpcId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rpcId_);
      }
      if (gzip_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, gzip_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cmd_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(params_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, params_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rpcToken_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, rpcToken_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wxd.boot.net.message.Rpc.ReqRemote)) {
        return super.equals(obj);
      }
      org.wxd.boot.net.message.Rpc.ReqRemote other = (org.wxd.boot.net.message.Rpc.ReqRemote) obj;

      if (getRpcId()
          != other.getRpcId()) return false;
      if (getGzip()
          != other.getGzip()) return false;
      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (!getParams()
          .equals(other.getParams())) return false;
      if (!getRpcToken()
          .equals(other.getRpcToken())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RPCID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRpcId());
      hash = (37 * hash) + GZIP_FIELD_NUMBER;
      hash = (53 * hash) + getGzip();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getParams().hashCode();
      hash = (37 * hash) + RPCTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getRpcToken().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wxd.boot.net.message.Rpc.ReqRemote parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wxd.boot.net.message.Rpc.ReqRemote parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wxd.boot.net.message.Rpc.ReqRemote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wxd.boot.net.message.Rpc.ReqRemote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wxd.boot.net.message.Rpc.ReqRemote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wxd.boot.net.message.Rpc.ReqRemote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wxd.boot.net.message.Rpc.ReqRemote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wxd.boot.net.message.Rpc.ReqRemote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.wxd.boot.net.message.Rpc.ReqRemote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.wxd.boot.net.message.Rpc.ReqRemote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wxd.boot.net.message.Rpc.ReqRemote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wxd.boot.net.message.Rpc.ReqRemote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wxd.boot.net.message.Rpc.ReqRemote prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *执行同步等待消息
     * </pre>
     *
     * Protobuf type {@code ReqRemote}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqRemote)
        org.wxd.boot.net.message.Rpc.ReqRemoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wxd.boot.net.message.Rpc.internal_static_ReqRemote_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wxd.boot.net.message.Rpc.internal_static_ReqRemote_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wxd.boot.net.message.Rpc.ReqRemote.class, org.wxd.boot.net.message.Rpc.ReqRemote.Builder.class);
      }

      // Construct using org.wxd.boot.net.message.Rpc.ReqRemote.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        rpcId_ = 0L;
        gzip_ = 0;
        cmd_ = "";
        params_ = "";
        rpcToken_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wxd.boot.net.message.Rpc.internal_static_ReqRemote_descriptor;
      }

      @java.lang.Override
      public org.wxd.boot.net.message.Rpc.ReqRemote getDefaultInstanceForType() {
        return org.wxd.boot.net.message.Rpc.ReqRemote.getDefaultInstance();
      }

      @java.lang.Override
      public org.wxd.boot.net.message.Rpc.ReqRemote build() {
        org.wxd.boot.net.message.Rpc.ReqRemote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wxd.boot.net.message.Rpc.ReqRemote buildPartial() {
        org.wxd.boot.net.message.Rpc.ReqRemote result = new org.wxd.boot.net.message.Rpc.ReqRemote(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.wxd.boot.net.message.Rpc.ReqRemote result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rpcId_ = rpcId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.gzip_ = gzip_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.cmd_ = cmd_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.params_ = params_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.rpcToken_ = rpcToken_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wxd.boot.net.message.Rpc.ReqRemote) {
          return mergeFrom((org.wxd.boot.net.message.Rpc.ReqRemote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wxd.boot.net.message.Rpc.ReqRemote other) {
        if (other == org.wxd.boot.net.message.Rpc.ReqRemote.getDefaultInstance()) return this;
        if (other.getRpcId() != 0L) {
          setRpcId(other.getRpcId());
        }
        if (other.getGzip() != 0) {
          setGzip(other.getGzip());
        }
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getParams().isEmpty()) {
          params_ = other.params_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getRpcToken().isEmpty()) {
          rpcToken_ = other.rpcToken_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                rpcId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                gzip_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                cmd_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                params_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                rpcToken_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long rpcId_ ;
      /**
       * <code>int64 rpcId = 1;</code>
       * @return The rpcId.
       */
      @java.lang.Override
      public long getRpcId() {
        return rpcId_;
      }
      /**
       * <code>int64 rpcId = 1;</code>
       * @param value The rpcId to set.
       * @return This builder for chaining.
       */
      public Builder setRpcId(long value) {

        rpcId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rpcId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRpcId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rpcId_ = 0L;
        onChanged();
        return this;
      }

      private int gzip_ ;
      /**
       * <pre>
       *1表示压缩过
       * </pre>
       *
       * <code>int32 gzip = 2;</code>
       * @return The gzip.
       */
      @java.lang.Override
      public int getGzip() {
        return gzip_;
      }
      /**
       * <pre>
       *1表示压缩过
       * </pre>
       *
       * <code>int32 gzip = 2;</code>
       * @param value The gzip to set.
       * @return This builder for chaining.
       */
      public Builder setGzip(int value) {

        gzip_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1表示压缩过
       * </pre>
       *
       * <code>int32 gzip = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGzip() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gzip_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <pre>
       *执行的命令
       * </pre>
       *
       * <code>string cmd = 3;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *执行的命令
       * </pre>
       *
       * <code>string cmd = 3;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *执行的命令
       * </pre>
       *
       * <code>string cmd = 3;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cmd_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *执行的命令
       * </pre>
       *
       * <code>string cmd = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        cmd_ = getDefaultInstance().getCmd();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *执行的命令
       * </pre>
       *
       * <code>string cmd = 3;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cmd_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object params_ = "";
      /**
       * <pre>
       *用JsonObject来解析
       * </pre>
       *
       * <code>string params = 4;</code>
       * @return The params.
       */
      public java.lang.String getParams() {
        java.lang.Object ref = params_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          params_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用JsonObject来解析
       * </pre>
       *
       * <code>string params = 4;</code>
       * @return The bytes for params.
       */
      public com.google.protobuf.ByteString
          getParamsBytes() {
        java.lang.Object ref = params_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          params_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用JsonObject来解析
       * </pre>
       *
       * <code>string params = 4;</code>
       * @param value The params to set.
       * @return This builder for chaining.
       */
      public Builder setParams(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        params_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用JsonObject来解析
       * </pre>
       *
       * <code>string params = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearParams() {
        params_ = getDefaultInstance().getParams();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用JsonObject来解析
       * </pre>
       *
       * <code>string params = 4;</code>
       * @param value The bytes for params to set.
       * @return This builder for chaining.
       */
      public Builder setParamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        params_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object rpcToken_ = "";
      /**
       * <pre>
       *用于验证的消息
       * </pre>
       *
       * <code>string rpcToken = 5;</code>
       * @return The rpcToken.
       */
      public java.lang.String getRpcToken() {
        java.lang.Object ref = rpcToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rpcToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用于验证的消息
       * </pre>
       *
       * <code>string rpcToken = 5;</code>
       * @return The bytes for rpcToken.
       */
      public com.google.protobuf.ByteString
          getRpcTokenBytes() {
        java.lang.Object ref = rpcToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rpcToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用于验证的消息
       * </pre>
       *
       * <code>string rpcToken = 5;</code>
       * @param value The rpcToken to set.
       * @return This builder for chaining.
       */
      public Builder setRpcToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        rpcToken_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用于验证的消息
       * </pre>
       *
       * <code>string rpcToken = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRpcToken() {
        rpcToken_ = getDefaultInstance().getRpcToken();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用于验证的消息
       * </pre>
       *
       * <code>string rpcToken = 5;</code>
       * @param value The bytes for rpcToken to set.
       * @return This builder for chaining.
       */
      public Builder setRpcTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        rpcToken_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReqRemote)
    }

    // @@protoc_insertion_point(class_scope:ReqRemote)
    private static final org.wxd.boot.net.message.Rpc.ReqRemote DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wxd.boot.net.message.Rpc.ReqRemote();
    }

    public static org.wxd.boot.net.message.Rpc.ReqRemote getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqRemote>
        PARSER = new com.google.protobuf.AbstractParser<ReqRemote>() {
      @java.lang.Override
      public ReqRemote parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReqRemote> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqRemote> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wxd.boot.net.message.Rpc.ReqRemote getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResRemoteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResRemote)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 rpcId = 1;</code>
     * @return The rpcId.
     */
    long getRpcId();

    /**
     * <pre>
     *1表示压缩过
     * </pre>
     *
     * <code>int32 gzip = 2;</code>
     * @return The gzip.
     */
    int getGzip();

    /**
     * <pre>
     *用JsonObject来解析
     * </pre>
     *
     * <code>string params = 3;</code>
     * @return The params.
     */
    java.lang.String getParams();
    /**
     * <pre>
     *用JsonObject来解析
     * </pre>
     *
     * <code>string params = 3;</code>
     * @return The bytes for params.
     */
    com.google.protobuf.ByteString
        getParamsBytes();

    /**
     * <pre>
     *用于验证的消息
     * </pre>
     *
     * <code>string rpcToken = 4;</code>
     * @return The rpcToken.
     */
    java.lang.String getRpcToken();
    /**
     * <pre>
     *用于验证的消息
     * </pre>
     *
     * <code>string rpcToken = 4;</code>
     * @return The bytes for rpcToken.
     */
    com.google.protobuf.ByteString
        getRpcTokenBytes();
  }
  /**
   * <pre>
   *执行同步等待消息
   * </pre>
   *
   * Protobuf type {@code ResRemote}
   */
  public static final class ResRemote extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResRemote)
      ResRemoteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResRemote.newBuilder() to construct.
    private ResRemote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResRemote() {
      params_ = "";
      rpcToken_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResRemote();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wxd.boot.net.message.Rpc.internal_static_ResRemote_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wxd.boot.net.message.Rpc.internal_static_ResRemote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wxd.boot.net.message.Rpc.ResRemote.class, org.wxd.boot.net.message.Rpc.ResRemote.Builder.class);
    }

    public static final int RPCID_FIELD_NUMBER = 1;
    private long rpcId_ = 0L;
    /**
     * <code>int64 rpcId = 1;</code>
     * @return The rpcId.
     */
    @java.lang.Override
    public long getRpcId() {
      return rpcId_;
    }

    public static final int GZIP_FIELD_NUMBER = 2;
    private int gzip_ = 0;
    /**
     * <pre>
     *1表示压缩过
     * </pre>
     *
     * <code>int32 gzip = 2;</code>
     * @return The gzip.
     */
    @java.lang.Override
    public int getGzip() {
      return gzip_;
    }

    public static final int PARAMS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object params_ = "";
    /**
     * <pre>
     *用JsonObject来解析
     * </pre>
     *
     * <code>string params = 3;</code>
     * @return The params.
     */
    @java.lang.Override
    public java.lang.String getParams() {
      java.lang.Object ref = params_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        params_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用JsonObject来解析
     * </pre>
     *
     * <code>string params = 3;</code>
     * @return The bytes for params.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParamsBytes() {
      java.lang.Object ref = params_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        params_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RPCTOKEN_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object rpcToken_ = "";
    /**
     * <pre>
     *用于验证的消息
     * </pre>
     *
     * <code>string rpcToken = 4;</code>
     * @return The rpcToken.
     */
    @java.lang.Override
    public java.lang.String getRpcToken() {
      java.lang.Object ref = rpcToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rpcToken_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用于验证的消息
     * </pre>
     *
     * <code>string rpcToken = 4;</code>
     * @return The bytes for rpcToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRpcTokenBytes() {
      java.lang.Object ref = rpcToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rpcToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rpcId_ != 0L) {
        output.writeInt64(1, rpcId_);
      }
      if (gzip_ != 0) {
        output.writeInt32(2, gzip_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(params_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, params_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rpcToken_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, rpcToken_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rpcId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rpcId_);
      }
      if (gzip_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, gzip_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(params_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, params_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rpcToken_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, rpcToken_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.wxd.boot.net.message.Rpc.ResRemote)) {
        return super.equals(obj);
      }
      org.wxd.boot.net.message.Rpc.ResRemote other = (org.wxd.boot.net.message.Rpc.ResRemote) obj;

      if (getRpcId()
          != other.getRpcId()) return false;
      if (getGzip()
          != other.getGzip()) return false;
      if (!getParams()
          .equals(other.getParams())) return false;
      if (!getRpcToken()
          .equals(other.getRpcToken())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RPCID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRpcId());
      hash = (37 * hash) + GZIP_FIELD_NUMBER;
      hash = (53 * hash) + getGzip();
      hash = (37 * hash) + PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getParams().hashCode();
      hash = (37 * hash) + RPCTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getRpcToken().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.wxd.boot.net.message.Rpc.ResRemote parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wxd.boot.net.message.Rpc.ResRemote parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wxd.boot.net.message.Rpc.ResRemote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wxd.boot.net.message.Rpc.ResRemote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wxd.boot.net.message.Rpc.ResRemote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wxd.boot.net.message.Rpc.ResRemote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wxd.boot.net.message.Rpc.ResRemote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wxd.boot.net.message.Rpc.ResRemote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.wxd.boot.net.message.Rpc.ResRemote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.wxd.boot.net.message.Rpc.ResRemote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.wxd.boot.net.message.Rpc.ResRemote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.wxd.boot.net.message.Rpc.ResRemote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.wxd.boot.net.message.Rpc.ResRemote prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *执行同步等待消息
     * </pre>
     *
     * Protobuf type {@code ResRemote}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResRemote)
        org.wxd.boot.net.message.Rpc.ResRemoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wxd.boot.net.message.Rpc.internal_static_ResRemote_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wxd.boot.net.message.Rpc.internal_static_ResRemote_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wxd.boot.net.message.Rpc.ResRemote.class, org.wxd.boot.net.message.Rpc.ResRemote.Builder.class);
      }

      // Construct using org.wxd.boot.net.message.Rpc.ResRemote.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        rpcId_ = 0L;
        gzip_ = 0;
        params_ = "";
        rpcToken_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wxd.boot.net.message.Rpc.internal_static_ResRemote_descriptor;
      }

      @java.lang.Override
      public org.wxd.boot.net.message.Rpc.ResRemote getDefaultInstanceForType() {
        return org.wxd.boot.net.message.Rpc.ResRemote.getDefaultInstance();
      }

      @java.lang.Override
      public org.wxd.boot.net.message.Rpc.ResRemote build() {
        org.wxd.boot.net.message.Rpc.ResRemote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.wxd.boot.net.message.Rpc.ResRemote buildPartial() {
        org.wxd.boot.net.message.Rpc.ResRemote result = new org.wxd.boot.net.message.Rpc.ResRemote(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.wxd.boot.net.message.Rpc.ResRemote result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rpcId_ = rpcId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.gzip_ = gzip_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.params_ = params_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.rpcToken_ = rpcToken_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wxd.boot.net.message.Rpc.ResRemote) {
          return mergeFrom((org.wxd.boot.net.message.Rpc.ResRemote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wxd.boot.net.message.Rpc.ResRemote other) {
        if (other == org.wxd.boot.net.message.Rpc.ResRemote.getDefaultInstance()) return this;
        if (other.getRpcId() != 0L) {
          setRpcId(other.getRpcId());
        }
        if (other.getGzip() != 0) {
          setGzip(other.getGzip());
        }
        if (!other.getParams().isEmpty()) {
          params_ = other.params_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getRpcToken().isEmpty()) {
          rpcToken_ = other.rpcToken_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                rpcId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                gzip_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                params_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                rpcToken_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long rpcId_ ;
      /**
       * <code>int64 rpcId = 1;</code>
       * @return The rpcId.
       */
      @java.lang.Override
      public long getRpcId() {
        return rpcId_;
      }
      /**
       * <code>int64 rpcId = 1;</code>
       * @param value The rpcId to set.
       * @return This builder for chaining.
       */
      public Builder setRpcId(long value) {

        rpcId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rpcId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRpcId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rpcId_ = 0L;
        onChanged();
        return this;
      }

      private int gzip_ ;
      /**
       * <pre>
       *1表示压缩过
       * </pre>
       *
       * <code>int32 gzip = 2;</code>
       * @return The gzip.
       */
      @java.lang.Override
      public int getGzip() {
        return gzip_;
      }
      /**
       * <pre>
       *1表示压缩过
       * </pre>
       *
       * <code>int32 gzip = 2;</code>
       * @param value The gzip to set.
       * @return This builder for chaining.
       */
      public Builder setGzip(int value) {

        gzip_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1表示压缩过
       * </pre>
       *
       * <code>int32 gzip = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGzip() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gzip_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object params_ = "";
      /**
       * <pre>
       *用JsonObject来解析
       * </pre>
       *
       * <code>string params = 3;</code>
       * @return The params.
       */
      public java.lang.String getParams() {
        java.lang.Object ref = params_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          params_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用JsonObject来解析
       * </pre>
       *
       * <code>string params = 3;</code>
       * @return The bytes for params.
       */
      public com.google.protobuf.ByteString
          getParamsBytes() {
        java.lang.Object ref = params_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          params_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用JsonObject来解析
       * </pre>
       *
       * <code>string params = 3;</code>
       * @param value The params to set.
       * @return This builder for chaining.
       */
      public Builder setParams(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        params_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用JsonObject来解析
       * </pre>
       *
       * <code>string params = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearParams() {
        params_ = getDefaultInstance().getParams();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用JsonObject来解析
       * </pre>
       *
       * <code>string params = 3;</code>
       * @param value The bytes for params to set.
       * @return This builder for chaining.
       */
      public Builder setParamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        params_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object rpcToken_ = "";
      /**
       * <pre>
       *用于验证的消息
       * </pre>
       *
       * <code>string rpcToken = 4;</code>
       * @return The rpcToken.
       */
      public java.lang.String getRpcToken() {
        java.lang.Object ref = rpcToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rpcToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用于验证的消息
       * </pre>
       *
       * <code>string rpcToken = 4;</code>
       * @return The bytes for rpcToken.
       */
      public com.google.protobuf.ByteString
          getRpcTokenBytes() {
        java.lang.Object ref = rpcToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rpcToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用于验证的消息
       * </pre>
       *
       * <code>string rpcToken = 4;</code>
       * @param value The rpcToken to set.
       * @return This builder for chaining.
       */
      public Builder setRpcToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        rpcToken_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用于验证的消息
       * </pre>
       *
       * <code>string rpcToken = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRpcToken() {
        rpcToken_ = getDefaultInstance().getRpcToken();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用于验证的消息
       * </pre>
       *
       * <code>string rpcToken = 4;</code>
       * @param value The bytes for rpcToken to set.
       * @return This builder for chaining.
       */
      public Builder setRpcTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        rpcToken_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResRemote)
    }

    // @@protoc_insertion_point(class_scope:ResRemote)
    private static final org.wxd.boot.net.message.Rpc.ResRemote DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.wxd.boot.net.message.Rpc.ResRemote();
    }

    public static org.wxd.boot.net.message.Rpc.ResRemote getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResRemote>
        PARSER = new com.google.protobuf.AbstractParser<ResRemote>() {
      @java.lang.Override
      public ResRemote parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResRemote> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResRemote> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.wxd.boot.net.message.Rpc.ResRemote getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqRemote_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReqRemote_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResRemote_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResRemote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tRpc.proto\"W\n\tReqRemote\022\r\n\005rpcId\030\001 \001(\003\022" +
      "\014\n\004gzip\030\002 \001(\005\022\013\n\003cmd\030\003 \001(\t\022\016\n\006params\030\004 \001" +
      "(\t\022\020\n\010rpcToken\030\005 \001(\t\"J\n\tResRemote\022\r\n\005rpc" +
      "Id\030\001 \001(\003\022\014\n\004gzip\030\002 \001(\005\022\016\n\006params\030\003 \001(\t\022\020" +
      "\n\010rpcToken\030\004 \001(\tB\032\n\030org.wxd.boot.net.mes" +
      "sageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ReqRemote_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReqRemote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReqRemote_descriptor,
        new java.lang.String[] { "RpcId", "Gzip", "Cmd", "Params", "RpcToken", });
    internal_static_ResRemote_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResRemote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResRemote_descriptor,
        new java.lang.String[] { "RpcId", "Gzip", "Params", "RpcToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
